/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2019-05-15 12:52:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dealer_005freg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.1.3.RELEASE.jar", Long.valueOf(1557833027013L));
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tjtyredevelopment30-04-2029/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1557833082022L));
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tjtyredevelopment30-04-2029/WEB-INF/lib/spring-webmvc-5.1.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1543290104000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t <meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css\\reset.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\style1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\table.css\">\r\n");
      out.write("\t<script src=\"js\\modernizr.js\"></script> \r\n");
      out.write("  \t <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<title>Dealer regisation</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t <script src=\"js\\jquery.menu-aim.js\"></script>\r\n");
      out.write("   <script src=\"js\\main.js\"></script> <!-- Resource jQuery -->\r\n");
      out.write("   <script src=\"js\\validation.js\"></script> \r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"TJTYRECOMPANY20-12-18\\src\\main\\webapp\\js\\Ajax.js\"> </script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/vue/dist/vue.js\"></script> \r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>    \r\n");
      out.write("         \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\t<script src=\"https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <header class=\"cd-main-header\">\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("            <a href=\"#0\" class=\"cd-nav-trigger\"><span></span></a>\r\n");
      out.write("            <nav class=\"cd-nav\">\r\n");
      out.write("                <ul class=\"cd-top-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p><a  href=\"logout\" style=\" text-decoration: none;\"><i class=\"fa fa-power-off\"></i>Logout</a></p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <main class=\"cd-main-content\">\r\n");
      out.write("            <nav class=\"cd-side-nav\">\r\n");
      out.write("                <br>\r\n");
      out.write("                <ul>\r\n");
      out.write("                \r\n");
      out.write("                   <li><a href=\"createcity\" style=\" text-decoration: none;\">City Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"role\" style=\" text-decoration: none;\">Role Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Poscreate\" style=\" text-decoration: none;\">POS Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"userregistration\"style=\" text-decoration: none;\">User Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"tyrecreate\" style=\" text-decoration: none;\">Item Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"item_price_assign\" style=\" text-decoration: none;\">Price Assignment</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Salereport\" style=\" text-decoration: none;\">Reports</a></li>\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createuserrolemappinglink\" style=\" text-decoration: none;\">User Role Assign</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"warehouseRegistration\" style=\" text-decoration: none;\">Warehouse Registration</a></li>\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createrolmodulemappinglink\" style=\" text-decoration: none;\">Role Module Assign</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createroleaccess\" style=\" text-decoration: none;\">Resource Role Access</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t <form action=\"create_Dealer\" method=\"POST\" id=\"form1\" name=\"CITYregistration\"  enctype=\"multipart/form-data\"  onSubmit=\"return validateForm()\"\">\r\n");
      out.write("\t             <div id=\"CITYregistration\">\r\n");
      out.write("               \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                            <div class=\"card-header\" style=\"background-color:lightblue\">\r\n");
      out.write("                              <center>  <font size=\"5px\" color=\"white\">\r\n");
      out.write("                                   Dealer registration\r\n");
      out.write("                                </font></center>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"cardpanel\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-4\">\r\n");
      out.write("                                          <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"dealerMailId\">dealer Mail Id</label></b>\r\n");
      out.write("                                                <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Mail Id\" name=\"dealer_Mail_Id\" required pattern=\"[^@]+@[^@]+\\.[a-zA-Z]{2,6}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t <style=\"color:red;\"> <span id=\"errmsg2\"></span></style>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                       \r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-md-4\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"Dealername\">Dealer name</label></b>\r\n");
      out.write("                                                <input type=\"text\"  class=\"form-control\" id=\"Dealername\" placeholder=\"Dealer name\" name=\"dealer_Name\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-4\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"password \">password </label></b>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"password\" placeholder=\"password\"  name=\"password \" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"Mobilenumber\">Mobile number</label></b>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"Mobilenumber\" placeholder=\"Mobile number\" name=\"phone_number\" required maxlength=\"10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:20px;\" id=\"mub\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"\">Address</label></b>\r\n");
      out.write("                                                <textarea class=\"form-control\" id=\"Address\" placeholder=\"Address\" name=\"address\" > </textarea required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:11px;\" id=\"GstAddres\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                             \r\n");
      out.write("\t\t\t\t\t\t\t <div class=\"col-md-4\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"City\">City</label></b>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"City\" placeholder=\"City\" name=\"city\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:20px;\" id=\"cty\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t           \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"State\">State</label></b>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"State\" placeholder=\"State\" name=\"state\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:20px;\" id=\"stat\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("                             <div class=\"form-group\">\r\n");
      out.write("                             <b><label for=\"pincode\">pincode</label></b>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\"  id=\"pincode\" placeholder=\"pincode\" name=\"pincode\" required maxlength=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:20px;\" id=\"gstno\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"col-md-4\">\r\n");
      out.write("                             <div class=\"form-group\">\r\n");
      out.write("                             <b><label for=\"channel Executive\">Channel Executive</label></b>\r\n");
      out.write("                                                 <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"channelExecutive\"  id=\"channelExecutive\" >\r\n");
      out.write("                                               <option value=\"\">select Channel Executive</option>\r\n");
      out.write("                                               ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                                </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><i style=\"color:red; font-size:20px;\" id=\"gstno\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                   \r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-md-4\"></div>\r\n");
      out.write("                                        <div class=\"col-md-1\">\r\n");
      out.write("                                         <input type=\"submit\" value=\"Done\" class=\"btn btn-danger\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-1\">\r\n");
      out.write("                                         <input type=\"reset\" value=\"Reset\" class=\"btn btn-danger\" >\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                        <div class=\"col-md-5\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                       </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <center>\r\n");
      out.write("                       \r\n");
      out.write("                  \r\n");
      out.write("                    </center>\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>dealer Mail Id</th>\r\n");
      out.write("                                <th>Dealer name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>password</th>\r\n");
      out.write("                                <th>Mobile number</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>City</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>State</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>pincode</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t </thead>\r\n");
      out.write("\t\t\t\t\t\t\t <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  ");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                       \r\n");
      out.write("                    </table>\r\n");
      out.write("                \r\n");
      out.write("            </div><!-- .content-wrapper -->\r\n");
      out.write("        </main> <!-- .cd-main-content -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {  \r\n");
      out.write("   $('form1').validate( {debug: true} );\r\n");
      out.write("   $(\"form1\").css({ 'color': 'red' });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //city validation\r\n");
      out.write("   $(document).ready(function () {\r\n");
      out.write("  $('#City').keypress(function (e) {\r\n");
      out.write("        var regex = new RegExp(\"^[a-zA-Z]+$\");\r\n");
      out.write("        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);\r\n");
      out.write("        if (regex.test(str)) {\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("        else\r\n");
      out.write("        {\r\n");
      out.write("        $(\"#cty\").html(\"characters Only\").show().fadeOut(\"slow\");\r\n");
      out.write("\t\t $(\"#cty\").css({ 'color': 'red' });\r\n");
      out.write("        return false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\t});\r\n");
      out.write("   //state validation\r\n");
      out.write("   $(document).ready(function () {\r\n");
      out.write("  $('#State').keypress(function (e) {\r\n");
      out.write("        var regex = new RegExp(\"^[a-zA-Z]+$\");\r\n");
      out.write("        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);\r\n");
      out.write("        if (regex.test(str)) {\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("        else\r\n");
      out.write("        {\r\n");
      out.write("        $(\"#stat\").html(\"characters Only\").show().fadeOut(\"slow\");\r\n");
      out.write("\t\t $(\"#stat\").css({ 'color': 'red' });\r\n");
      out.write("        return false;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#Mobilenumber\").keypress(function (e) {\r\n");
      out.write("     //if the letter is not digit then display error and don't type anything\r\n");
      out.write("     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {\r\n");
      out.write("        //display error message\r\n");
      out.write("        $(\"#mub\").html(\"Digits Only\").show().fadeOut(\"slow\");\r\n");
      out.write("\t\t$(\"#mub\").css({ 'color': 'red' });\r\n");
      out.write("               return false;\r\n");
      out.write("    }\r\n");
      out.write("   });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#pincode\").keypress(function (e) {\r\n");
      out.write("     //if the letter is not digit then display error and don't type anything\r\n");
      out.write("     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {\r\n");
      out.write("        //display error message\r\n");
      out.write("        $(\"#gstno\").html(\"Digits Only\").show().fadeOut(\"slow\");\r\n");
      out.write("\t\t$(\"#gstno\").css({ 'color': 'red' });\r\n");
      out.write("               return false;\r\n");
      out.write("    }\r\n");
      out.write("   });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/dealer_reg.jsp(161,47) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("ce");
      // /WEB-INF/pages/dealer_reg.jsp(161,47) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/dealer_reg.jsp(161,47) '${chhanelExecutive }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${chhanelExecutive }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                                <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ ce.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ce.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ce.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                                               ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/pages/dealer_reg.jsp(206,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("city");
      // /WEB-INF/pages/dealer_reg.jsp(206,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/dealer_reg.jsp(206,7) '${allCity}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allCity}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.cityname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.gstno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.gstaddres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.cityname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.gstno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.gstaddres}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/pages/dealer_reg.jsp(219,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/deletecity");
      // /WEB-INF/pages/dealer_reg.jsp(219,9) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("deleteUrl");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }
}
