/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2019-05-15 20:13:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class warehouse_005fregistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tjtyredevelopment30-04-2029/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1557833082022L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t<!-- <meta charset=\"UTF-8\"> -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css\\reset.css\"> \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\style1.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css\\table.css\">\r\n");
      out.write("\t<script src=\"js\\modernizr.js\"></script> \r\n");
      out.write("  \t <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<title>WAREHOUSE REGISTRATION </title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t <script src=\"js\\jquery.menu-aim.js\"></script>\r\n");
      out.write("   <script src=\"js\\main.js\"></script> <!-- Resource jQuery -->\r\n");
      out.write("   <script src=\"js\\validation.js\"></script> \r\n");
      out.write("    <script type=\"TJTYRECOMPANY20-12-18\\src\\main\\webapp\\js\\Ajax.js\"> </script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function wareHouseValidation(){\r\n");
      out.write("\t\tif((document.getElementById('warehouse_Id').value==\"\"))\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t  document.getElementById('error').innerHTML = \"Please enter  warehouse_Id\";\r\n");
      out.write("\t\t  Warehouseregistration.warehouse_Id.focus();\r\n");
      out.write("\t\t  return(false);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t return(true);\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <style>\r\n");
      out.write("\t \t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".colors {\r\n");
      out.write(" \r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".dropdown dd, .dropdown dt {\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown ul {\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dd {\r\n");
      out.write("    position:relative;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown a, .dropdown a:visited {\r\n");
      out.write("    color:green;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    outline:none;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("    min-height: 30px;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dt a {\r\n");
      out.write("    background-color:lightblue;\r\n");
      out.write("\twidth:32%;\r\n");
      out.write("    display:block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    \r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dt a span, .multiSel span {\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    display:inline-block;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:5px 10px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dd ul {\r\n");
      out.write("    background-color:lightblue;\r\n");
      out.write("    top:1px;\r\n");
      out.write("    color:green;\r\n");
      out.write("    display:none;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    width:32%;\r\n");
      out.write("    list-style:none;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown span.value {\r\n");
      out.write("    display:none;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dd ul li a {\r\n");
      out.write("    display:block;\r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write(".dropdown dd ul li a:hover {\r\n");
      out.write("  \r\n");
      out.write("    margin:0px;\r\n");
      out.write("    padding:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn{\r\n");
      out.write("position:absolute;\r\n");
      out.write("right:40%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"cd-main-header\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a href=\"#0\" class=\"cd-nav-trigger\"><span></span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"cd-nav\">\r\n");
      out.write("\t\t\t<ul class=\"cd-top-nav\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li >\r\n");
      out.write("\t\t\t\t\t <p><a  href=\"logout\" style=\" text-decoration: none;\"><i class=\"fa fa-power-off\"></i>Logout</a></p>\r\n");
      out.write("</li>\r\n");
      out.write("\t</header> \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<main class=\"cd-main-content\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<nav class=\"cd-side-nav\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createcity\" style=\" text-decoration: none;\">City Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"role\" style=\" text-decoration: none;\">Role Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Poscreate\" style=\" text-decoration: none;\">POS Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"userregistration\"style=\" text-decoration: none;\">User Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"tyrecreate\" style=\" text-decoration: none;\">Item Registration</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"item_price_assign\" style=\" text-decoration: none;\">Price Assignment</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Salereport\" style=\" text-decoration: none;\">Reports</a></li>\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createuserrolemappinglink\" style=\" text-decoration: none;\">User Role Assign</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"warehouseRegistration\" style=\" text-decoration: none;\">Warehouse Registration</a></li>\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createrolmodulemappinglink\" style=\" text-decoration: none;\">Role Module Assign</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"createroleaccess\" style=\" text-decoration: none;\">Resource Role Access</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t <div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t   <div class=\"container\">\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("           \r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("                 \r\n");
      out.write("\t\t\t\t\t <div class=\"card-header\" style=\"background-color:lightblue\">\r\n");
      out.write("                             <font size=\"5px\" color=\"white\">\r\n");
      out.write("                              WAREHOUSE REGISTRATION \r\n");
      out.write("                                </font>\r\n");
      out.write("                            </div>\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <form action=\"createwarehouse\" method=\"POST\"  name=\"Warehouseregistration\" enctype=\"multipart/form-data\"  onsubmit=\"return wareHouseValidation()\">\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"warehouseid\">warehouse ID</label></b>\r\n");
      out.write("                                              <!--   <input type=\"text\" class=\"form-control\" id=\"warehouseID\" placeholder=\"Enter warehouse ID\" id=\"warehouse_Id\" name=\"warehouse_Id\" > -->\r\n");
      out.write("                                          <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"warehouse_Id\"  id=\"warehouse_Id\" >\r\n");
      out.write("                                           <option value=\"\">select WareHouse</option>\r\n");
      out.write("                                               \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t   <div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                               <b><label for=\"module\">Module</label></b>\r\n");
      out.write("                                               \r\n");
      out.write("                   \t\t\t\t       \t  <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"module_Id\"  id=\"module\" >\r\n");
      out.write("                                           <option value=\"\">select Module</option>\r\n");
      out.write("                                               \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                               \r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                 <b><label for=\"raisedby\">Lable</label></b>\r\n");
      out.write("                   \t\t\t\t       \t  <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"label\"  id=\"label\" >\r\n");
      out.write("                                               <option value=\"\">select Lable</option>\r\n");
      out.write("                                              \r\n");
      out.write("                                               </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t      <div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                 <b><label for=\"role\">Role</label></b>\r\n");
      out.write("                   \t\t\t\t       \t  <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"role\"  id=\"role\" >\r\n");
      out.write("                                               <option value=\"\">select Role</option>\r\n");
      out.write("                                           \r\n");
      out.write("                                               \r\n");
      out.write("                                               </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group\">\r\n");
      out.write("                                                <b><label for=\"userId\">User id</label></b>\r\n");
      out.write("                                            <select class=\"form-control\" class=\"form-control chosen-select\"  name=\"userid\"  id=\"userID\" >\r\n");
      out.write("                                               <option value=\"\">select User id</option>\r\n");
      out.write("                                               \r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"col-md-4\">\r\n");
      out.write("                                            <div class=\"form-group  dropdown\">\r\n");
      out.write("                                                <b><label for=\"size\">Level</label></b>\r\n");
      out.write("<select class=\"form-control\" class=\"form-control chosen-select\"  name=\"level\"  id=\"level\" >\r\n");
      out.write("                                               <option value=\"\">select Level</option>\r\n");
      out.write("                                           \t\t\t\t\t\t\t\t\t   \r\n");
      out.write("                                                </select>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \r\n");
      out.write("                                     <br>    \r\n");
      out.write("                                      <div class=\"output\">\r\n");
      out.write("  <div id=\"red\" class=\"colors\">  \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    <dl class=\"dropdown\"> <dt>\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <span class=\"hida \">- - Select city child - -</span>    \r\n");
      out.write("      <p class=\"multiSel\"></p>  \r\n");
      out.write("    </a>\r\n");
      out.write("    </dt>\r\n");
      out.write("\r\n");
      out.write("    <dd>\r\n");
      out.write("        <div class=\"mutliSelect\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\"city1\" />city1</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\"city2\" />city2</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\"city3\" />city3</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\"city4\" />city4</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\"city5\" />city5</li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dd>\r\n");
      out.write("</dl>\r\n");
      out.write("    \r\n");
      out.write("   </div> \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div id=\"yellow\" class=\"colors yellow\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <dl class=\"dropdown\"> <dt>\r\n");
      out.write("    <a href=\"#\">\r\n");
      out.write("      <span class=\"hida\">- Select city warehouse-</span>    \r\n");
      out.write("      <p class=\"multiSel\"></p>  \r\n");
      out.write("    </a>\r\n");
      out.write("    </dt>\r\n");
      out.write("\r\n");
      out.write("    <dd>\r\n");
      out.write("        <div class=\"mutliSelect\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse1\" /> warehouse1</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse2\" /> warehouse2</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse3\" /> warehouse3</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse4\" /> warehouse4</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse5\" /> warehouse5</li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <input type=\"checkbox\" value=\" warehouse6\" /> warehouse6</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dd>\r\n");
      out.write("</dl>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("                                     \r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("                <input type=\"submit\"  class=\"btn btn-danger submit-button\" value=\"Save\"><br><br>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>warehouseID </th>\r\n");
      out.write("                                <th>module</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                                <th>role</th>\r\n");
      out.write("                                <th>userID</th>\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t </thead>\r\n");
      out.write("\t\t\t\t\t\t\t <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  <spring:url value=\"/deletecity\" var=\"deleteUrl\"/>\r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                       \r\n");
      out.write("                    </table>\r\n");
      out.write("            \r\n");
      out.write("                 \r\n");
      out.write("            \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t \t\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</main> <!-- .cd-main-content -->\r\n");
      out.write("\t<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("  \r\n");
      out.write("  $(\"form[name='requisitionorder']\").validate({\r\n");
      out.write("   \r\n");
      out.write("    rules: {\r\n");
      out.write("      \r\n");
      out.write("    \tmodule: \"required\",\r\n");
      out.write("    \tlabel:\"required\",\r\n");
      out.write("      role: \"required\",\r\n");
      out.write("      userID: \"required\",\r\n");
      out.write("\t  level: \"required\",\r\n");
      out.write("\t  \r\n");
      out.write("\t \r\n");
      out.write("     \r\n");
      out.write("\t  \r\n");
      out.write("    },\r\n");
      out.write("   \r\n");
      out.write("    messages: {\r\n");
      out.write("    \tmodule: \"Please enter your  sourceid\",\r\n");
      out.write("    \tlabel: \"Please enter  role\",\r\n");
      out.write("    \trole: \"Please enter your raisedby\",\r\n");
      out.write("    \tuserID: \"Please enter expecteddate\",\r\n");
      out.write("    \tlevel: \"Please enter your tyrepattern\",\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t\r\n");
      out.write("    },\r\n");
      out.write("    \r\n");
      out.write("    submitHandler: function(form) {\r\n");
      out.write("      form.submit();\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("  //called when key is pressed in textbox\r\n");
      out.write("  $(\"#quantity\").keypress(function (e) {\r\n");
      out.write("     //if the letter is not digit then display error and don't type anything\r\n");
      out.write("     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {\r\n");
      out.write("        //display error message\r\n");
      out.write("        $(\"#errmsg\").html(\"Digits Only\").show().fadeOut(\"slow\");\r\n");
      out.write("               return false;\r\n");
      out.write("    }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("  $('#colorselector').change(function(){\r\n");
      out.write("    $('.colors').hide();\r\n");
      out.write("    $('#' + $(this).val()).show();\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("// [forked from](http://jsfiddle.net/FvMYz/)\r\n");
      out.write("// [show-hide-based-on-select-option-jquery)(http://stackoverflow.com/questions/2975521/show-hide-div-based-on-select-option-jquery/2975565#2975565)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\".dropdown dt a\").on('click', function () {\r\n");
      out.write("    $(\".dropdown dd ul\").slideToggle('fast');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\".dropdown dd ul li a\").on('click', function () {\r\n");
      out.write("    $(\".dropdown dd ul\").hide();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function getSelectedValue(id) {\r\n");
      out.write("    return $(\"#\" + id).find(\"dt a span.value\").html();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).bind('click', function (e) {\r\n");
      out.write("    var $clicked = $(e.target);\r\n");
      out.write("    if (!$clicked.parents().hasClass(\"dropdown\")) ;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('.mutliSelect input[type=\"checkbox\"]').on('click', function () {\r\n");
      out.write("\r\n");
      out.write("    var title = $(this).closest('.mutliSelect').find('input[type=\"checkbox\"]').val(),\r\n");
      out.write("        title = $(this).val() + \",\";\r\n");
      out.write("\r\n");
      out.write("    if ($(this).is(':checked')) {\r\n");
      out.write("        var html = '<span title=\"' + title + '\">' + title + '</span>';\r\n");
      out.write("        $('.multiSel').append(html);\r\n");
      out.write("        $(\".hida\").hide();\r\n");
      out.write("    } else {\r\n");
      out.write("        $('span[title=\"' + title + '\"]').remove();\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('.add').click(function(){\r\n");
      out.write("        $(\"#tes\").append('<br><div class=\"row\"><div class=\"col-md-3\"></div><br> <div class=\"col-md-3\"><select name=\"LIVINGSTYLE\" id=\"test\">'+\r\n");
      out.write("                          '<option value=\"1\">Option 1</option>'+\r\n");
      out.write("                          '<option value=\"2\">Option 2</option>'+\r\n");
      out.write("                          '<option value=\"3\">Option 3</option>'+\r\n");
      out.write("                          '<option value=\"4\">Option 4</option>'+\r\n");
      out.write("                        '</select></div><br> <div class=\"col-md-3\"><select name=\"LIVINGSTYLE\" id=\"test\">'+\r\n");
      out.write("                          '<option value=\"1\">Option 1</option>'+\r\n");
      out.write("                          '<option value=\"2\">Option 2</option>'+\r\n");
      out.write("                          '<option value=\"3\">Option 3</option>'+\r\n");
      out.write("                          '<option value=\"4\">Option 4</option>'+\r\n");
      out.write("                        '</select></div><br>  <div class=\"col-md-3\"><input type=\"text\"></div> <div><a href=\"javascript:void(0);\" class=\"remCF\">Remove</a></div></div>');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("// lable according to module\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#module').on('change', function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar module = $('#module').val();\r\n");
      out.write("\tdebugger;\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t            type: \"GET\",\r\n");
      out.write("\t            contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t         \t  datatype: \"json\",\r\n");
      out.write("\t            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/allLevelByModuleId/\"+module+\"\",\r\n");
      out.write("\t            success: function (response) {\r\n");
      out.write("\t                 var label=\"\";\r\n");
      out.write("\t                \r\n");
      out.write("\t               \r\n");
      out.write("\t                 label+=\"<option value='\"+response[i]+\"'>Select Lables</option>\"\r\n");
      out.write("\t                  for(var i=0;i<response.length;i++){ \r\n");
      out.write("\t                \t \r\n");
      out.write("\t                \t  label+=\"<option value='\"+response[i]+\"'>\"+response[i]+\"</option>\"\r\n");
      out.write("\t                \t $('#label').html(label);\r\n");
      out.write("\t                \t  debugger;\r\n");
      out.write("\t                \t\r\n");
      out.write("\t                }\r\n");
      out.write("\t                 \r\n");
      out.write("\t                 \r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function(e){\r\n");
      out.write("\t            \t debugger;\r\n");
      out.write("\t            \tconsole.log(\"error\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// role according to module_id and lable\r\n");
      out.write("\t\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#label').on('change', function(){\r\n");
      out.write("\t\tvar module = $('#module').val();\r\n");
      out.write("\t\tvar label = $('#label').val();\r\n");
      out.write("\t\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t            type: \"GET\",\r\n");
      out.write("\t            contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t         \t  datatype: \"json\",\r\n");
      out.write("\t            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/allRoleByModuleIdAndLevel/\"+module+\",\"+label+\"\",\r\n");
      out.write("\t            success: function (response) {\r\n");
      out.write("\t                 var role=\"\";\r\n");
      out.write("\t                 \r\n");
      out.write("\t              \r\n");
      out.write("\t                 role+=\"<option value='\"+response[i]+\"'>Select Role</option>\"\r\n");
      out.write("\t                  for(var i=0;i<response.length;i++){ \r\n");
      out.write("\t                \t \r\n");
      out.write("\t                \t  role+=\"<option value='\"+response[i]+\"'>\"+response[i]+\"</option>\"\r\n");
      out.write("\t                \t $('#role').html(role);\r\n");
      out.write("\t                \t \r\n");
      out.write("\t                }\r\n");
      out.write("\t                 \r\n");
      out.write("\t                 \r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function(e){\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \t\r\n");
      out.write("\t            \tconsole.log(\"error\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// user_id according to role \r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t$('#role').on('change', function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar role = $('#role').val();\r\n");
      out.write("\tdebugger;\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t            type: \"GET\",\r\n");
      out.write("\t            contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t         \t  datatype: \"json\",\r\n");
      out.write("\t            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/allUserIdByRole/\"+role+\"\",\r\n");
      out.write("\t            success: function (response) {\r\n");
      out.write("\t                 var userID=\"\";\r\n");
      out.write("\t   \t\r\n");
      out.write("\t                 userID+=\"<option value='\"+response[i]+\"'>Select Lables</option>\"\r\n");
      out.write("\t                  for(var i=0;i<response.length;i++){ \r\n");
      out.write("\t                \r\n");
      out.write("\t                \t  userID+=\"<option value='\"+response[i]+\"'>\"+response[i]+\"</option>\"\r\n");
      out.write("\t                \t $('#userID').html(userID);\r\n");
      out.write("\t                \r\n");
      out.write("\t                \t\r\n");
      out.write("\t                }\r\n");
      out.write("\t                 \r\n");
      out.write("\t                 \r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function(e){\r\n");
      out.write("\t            \t\r\n");
      out.write("\t        \r\n");
      out.write("\t            \tconsole.log(\"error\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t });\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#userID').on('change', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar level = $('#label').val();\r\n");
      out.write("\t\tdebugger;\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t            type: \"GET\",\r\n");
      out.write("\t\t            contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("\t\t         \t  datatype: \"json\",\r\n");
      out.write("\t\t            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/allLevelByLevelPath/\"+level+\"\",\r\n");
      out.write("\t\t            success: function (response) {\r\n");
      out.write("\t\t                 var userID=\"\";\r\n");
      out.write("\t\t   \t\r\n");
      out.write("\t\t                 userID+=\"<option value='\"+response[i]+\"'>Select Lables</option>\"\r\n");
      out.write("\t\t                  for(var i=0;i<response.length;i++){ \r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t  userID+=\"<option value='\"+response[i]+\"'>\"+response[i]+\"</option>\"\r\n");
      out.write("\t\t                \t $('#level').html(userID);\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                 \r\n");
      out.write("\t\t                 \r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            error: function(e){\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t            \tconsole.log(\"error\");\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t        \r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/pages/warehouse_registration.jsp(182,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty warehouse_registration}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<script>popup('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse_registration}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("') </script>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/warehouse_registration.jsp(206,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("warehouse");
      // /WEB-INF/pages/warehouse_registration.jsp(206,48) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/warehouse_registration.jsp(206,48) '${allWareHouseId}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allWareHouseId}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.warehouse_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.warehouse_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('(');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${warehouse.warehouse_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/pages/warehouse_registration.jsp(222,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("moduleID");
      // /WEB-INF/pages/warehouse_registration.jsp(222,48) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/warehouse_registration.jsp(222,48) '${allHierarchyModule}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allHierarchyModule}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${moduleID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${moduleID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/pages/warehouse_registration.jsp(386,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("wh");
      // /WEB-INF/pages/warehouse_registration.jsp(386,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/warehouse_registration.jsp(386,7) '${allWarehouse}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${allWarehouse}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wh.warehouse_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wh.module_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wh.role}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wh.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
